export const foods = [{
    id: 1,
    name: 'cold brew',
    price: 5.99,
    type: 'drink',
}, {
    id: 2,
    name: 'cappucino',
    price: 4.99,
    type: 'drink',
}, {
    id: 3,
    name: 'espresso',
    price: 4.99,
    type: 'drink',
}, {
    id: 4,
    name: 'americano',
    price: 4.49,
    type: 'drink',
}, {
    id: 5,
    name: 'latte',
    price: 5.99,
    type: 'drink',
}, {
    id: 6,
    name: 'iced coffee',
    price: 3.99,
    type: 'drink',
}, {
    id: 7,
    name: 'macchiato',
    price: 5.99,
    type: 'drink',
}, {
id: 8,
    name: 'hot coffee',
    price: 3.99,
    type: 'drink',
}, {
    id: 9,
    name: 'cinnamon roll',
    price: 4.99,
    type: 'pastry',
    description: 'big, fluffy, and soft',
}, {
    id: 10,
    name: 'scone',
    price: 3.99,
    type: 'pastry',
    description: 'the american kind, blueberries inside',
}, {
    id: 11,
    name: 'muffin',
    price: 4.99,
    type: 'pastry',
    description: 'comes in plain, chocolate chip, and pumpkin',
}, {
    id: 12,
    name: 'croissant',
    price: 4.99,
    type: 'pastry',
    description: 'the flaky, french classic',
}, {
    id: 13,
    name: 'eclair',
    price: 4.49,
    type: 'pastry',
    description: 'frosting comes in chocolate or salted caramel',
}, {
    id: 14,
    name: 'tiramisu',
    price: 5.99,
    type: 'pastry',
    description: 'a coffee flavoured italian dessert',
}, {
    id: 15,
    name: 'brookie',
    price: 5.49,
    type: 'pastry',
    description: 'half brownie, half cookie',
}, {    
    id: 16,
    name: 'egg & cheese',
    price: 6.49,
    type: 'lunch',
    description: 'on five-grain bread, or a bagel',
}, {    
    id: 17,
    name: 'avocado toast',
    price: 8.49,
    type: 'lunch',
    description: 'on multigrain bread with olive oil and sea salt',
}, {    
    id: 18,
    name: 'oatmeal',
    price: 5.99,
    type: 'lunch',
    description: 'steamed milk, raisins, cinnamon, & honey',
}, {    
    id: 19,
    name: 'grilled cheese',
    price: 7.49,
    type: 'lunch',
    description: 'on multigrain bread with cheddar',
}, {    
    id: 21,
    name: 'vegan egg & cheese',
    price: 6.49,
    type: 'lunch',
    description: 'on an english muffin',
}, {
    id: 20,
    name: 'nyc bagel',
    price: 10.49,
    type: 'lunch',
    description: 'smoked salmon, cream cheese, & capers',
}]